### ISSUE TITLE
Modulus operator

### ISSUE THREAD

**Issue by oscar-broman** [Zeex/samp-plugin-jit#42]
I thought I was going crazy, but after some debugging I realized it was not my fault!

Negative numbers remain negative.

```c++
public OnFilterScriptInit() {
	new a = -5, b = 10;
	printf("-5 %% 10 = %d", a % b);
}
```

Output:

```
[00:39:30] -5 % 10 = -5
```

**Comment by Zeex** [comment]
Fixed, thanks!
