### ISSUE TITLE
Server hanging

### ISSUE THREAD

**Issue by oscar-broman** [Zeex/samp-plugin-jit#44]
When I'm using this plugin, sometimes my server will become unresponsive. In the SA-MP browser, I still see the same number of players online (and the player list with nicknames), but there is actually nobody online and players can't connect.

How do I debug things like this?

**Comment by oscar-broman** [comment]
Alright. I will investigate. An option to enable logging (perhaps even a backtrace) when a `BOUNDS` opcode fails would be really helpful, however.

**Comment by Zeex** [comment]
Yeah, I should add something like that.

For the time being I have an idea: add a debug break inside the bounds opcode like this:

```c++
  ...
  asm_.bind(halt_label);
    asm_.int3();                   // int 3 = debug break
    asm_.mov(edi, AMX_ERR_BOUNDS);
    asm_.jmp(halt_helper_label_);
  asm_.bind(exit_label);
```

and run the server under gdb, so when the bounds check fails gdb will stop immediately (with a SIGTRAP signal) giving you a chance to get a stack trace.

It would be possible then to use the debugging method described on the wiki to find the location of that bounds opcode (using a modified pawndisasm).
