### ISSUE TITLE
Floating-point native calls

### ISSUE THREAD

**Issue by oscar-broman** [Zeex/samp-plugin-jit#45]
It seems `floatcmp` is still invoked. Couldn't this be replaced by an instruction from the x87 FPU set?

The same goes for `floattan`, `atan2`, `floatsin`, `floatcos`, `floatfract`, and probably a few other functions.

```pawn
main() {
    new Float:a = 2.0, Float:b = 2.0;

    if (a == b) {
        printf("equal");
    }
}
```

By the way, what happened to the donate link?

**Comment by Zeex** [comment]
IIRC those were a bit more complex than the rest (e.g. they had branches) so I didn't include them. I'm not even sure if there's any performance benefits from rewriting all these float functions in asm, I'll need to do some benchmarks.

As for the donate button: I remove it (tax complications).

**Comment by Zeex** [comment]
Added benchmarks for currnetly implemented FP functions, the results were quite satisfying:

```
floatabs: 2025 ticks (100000000 iterations)
floatadd: 2155 ticks (100000000 iterations)
floatdiv: 2152 ticks (100000000 iterations)
floatlog: 8133 ticks (100000000 iterations)
floatmul: 2154 ticks (100000000 iterations)
floatsqroot: 3359 ticks (100000000 iterations)
floatsub: 2119 ticks (100000000 iterations)
```

vs.

```
floatabs: 235 ticks (100000000 iterations)
floatadd: 218 ticks (100000000 iterations)
floatdiv: 328 ticks (100000000 iterations)
floatlog: 6285 ticks (100000000 iterations)
floatmul: 218 ticks (100000000 iterations)
floatsqroot: 326 ticks (100000000 iterations)
floatsub: 216 ticks (100000000 iterations)
```

I guess I should do the rest of them too.

**Comment by oscar-broman** [comment]
Satisfying indeed!

**Comment by Zeex** [comment]
I added `floatcmp`, you probably already noticed.  I also implemented a few others (`floatsin`, `floatround`, `floatfract`) but they weren't much of an improvement so I decided not to add them. `floatlog` is probably worth removing too.

**Comment by oscar-broman** [comment]
Nice. What about `float`? Furthermore, I suppose it could be optimized away in cases such as the following:

```pawn
stock AcceptsFloat(Float:value) {
    return value;
}

AcceptsFloat(123); // AcceptsFloat(float(123))
AcceptsFloat(123.0); // AcceptsFloat(123.0)
```

Though I suppose that unless misused in heavy loops, it wouldn't make a very big difference.

**Comment by Zeex** [comment]
`float` is already there: https://github.com/Zeex/samp-plugin-jit/blob/master/src/amxjit/compiler-asmjit.cpp#L1177

**Comment by oscar-broman** [comment]
Oh, that's right. I suppose that wraps up this issue.

Much appreciated!

**Comment by Zeex** [comment]
Pushed code for those float functions that didn't make it, in case somebody would like to tinker with them:

https://github.com/Zeex/samp-plugin-jit/tree/floatsin
https://github.com/Zeex/samp-plugin-jit/tree/floatround
