### ISSUE TITLE
Idea about LCTRL 6

### ISSUE THREAD

**Issue by oscar-broman** [Zeex/samp-plugin-jit#46]
Correct me if I'm wrong, but `LCTRL 6` never appears in the AMX unless `#emit` is used?

If that's the case, the JIT compiler could be clever and replace that with `PUSH.pri` followed by the address (and remove the next push), thus making many broken libs work again.

**Comment by Zeex** [comment]
Can you please remind me what was the problem with `lctrl 6`? I looked at the code for `lctrl 6` but it looked like it should be working as is, maybe I'm missing something.

**Comment by oscar-broman** [comment]
I realize now that something else must have been the culprit for crash issues I had, perhaps the issue I created in amx_assembly.

I'll close this for now.
