### ISSUE TITLE
floatlog is slower with jit.

### ISSUE THREAD

**Issue by raefaldhia** [Zeex/samp-plugin-jit#50]
When i ran benchmark, floatlog is 2x slower if i use jit.
https://github.com/Zeex/samp-plugin-jit/tree/master/benchmarks

**Comment by Zeex** [comment]
Indeed it does seem to be slower, I guess it depends on the CPU model - when I had my old computer with an i3-2100 it used to be slightly faster IIRC. 

Thanks for bringing this to my attention, sorry that it took me more than 2 years to reply 👍

**Comment by Zeex** [comment]
In 2.3 floatlog() has been removed, calls to this function now use the standard amxFloat implementation (same as without JIT). Maybe it will be optimized in a future version.
