### ISSUE TITLE
IsJITPresent returns false in OnJITCompile

### ISSUE THREAD

**Issue by Y-Less** [Zeex/samp-plugin-jit#53]
Since that callback is the place to do JIT-compatible rewriting, this seems like the number one place to want that function to work.  I realise that the obvious response is "if that callback was called, of COURSE the JIT exists", but generic code may not know where it was called from without extensive passing around of data.

**Comment by Y-Less** [comment]
For the same reason, the `IsJITASMJumpCapable` function I proposed also doesn't work in that callback.

**Comment by Y-Less** [comment]
I wrote a few different functions to handle different cases.  The naming of `IsJITPresent` implies to me that it should always return `true` even when it isn't in use or failed.  However, backwards compatability may be better and so an alternate function for that use might be preferred.

**Comment by Zeex** [comment]
I need to debug `__JIT` more to cover cases where `OnJITCompile` returns 0 or compilation fails. I suppose `__JIT` should be set to false in those cases.

**Comment by Y-Less** [comment]
I did actually write a few more callbacks: `OnJITCompile(success)` and `OnJITCapabilities(capabilities)` (I don't like that name `OnJITLoad(capabilities)` is better), however I removed them before an old pull request:

https://github.com/Zeex/samp-plugin-jit/pull/52/commits/ff882b069a93c26852475028a3fffd9ee7360d79
https://github.com/Zeex/samp-plugin-jit/pull/52/commits/3acafa285d71e145f430bd9ec958aebcaf847bf0
