### ISSUE TITLE
`alt` not preserved across SYSREQ.C calls.

### ISSUE THREAD

**Issue by Y-Less** [Zeex/samp-plugin-jit#54]
`pri` is the return value, so obviously will be clobbered, but I'm pretty sure `alt` shouldn't be affected.

**Comment by Y-Less** [comment]
Just spent several hours debugging a crash that came down to this!

**Comment by Y-Less** [comment]
Had a quick look myself, but wasn't sure of a good way to solve it, since it can't be put on the stack as that will mess up the call, and can't be put in a global as you can call a native from inside a function called by a native called by function (`CallLocalFunction` etc).

**Comment by Zeex** [comment]
It seems that all registers are already used, for something, there is kind of no place for `alt` to live now... I'll try to find a place for it.
