### ISSUE TITLE
[error]ubuntu 14.04

### ISSUE THREAD

**Issue by Romz24** [Zeex/samp-plugin-jit#58]
how to fix this error?
os: ubuntu 14.04 64bit

`./samp03svr: relocation error: plugins/jit.so: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`

**Comment by Zeex** [comment]
Try compiling the plugin on your Ubuntu system, it will solve the issue. This link explains how: https://github.com/Zeex/jit#building-on-linux

**Comment by Romz24** [comment]
I can not do it.


![kkf5illsqxy](https://user-images.githubusercontent.com/2458113/43157630-3f6f3ddc-8f86-11e8-830f-c7fa85ac6d1a.jpg)

**Comment by Zeex** [comment]
That is strange, I've just compiled on Ubuntu 14.04 without any errors... You probably have a different version of GCC, mine is 4.8.

Anyway, try this version: [jit-2.2-linux.tar.gz](https://github.com/Zeex/samp-plugin-jit/files/2224948/jit-2.2-linux.tar.gz)

**Comment by Romz24** [comment]
Can you give me your discord or skype? I'll give you root access, you'll try to compile.

**Comment by Zeex** [comment]
Can you show the output of `gcc --version`?

**Comment by Romz24** [comment]
`gcc (Ubuntu 4.8.5-4ubuntu8~14.04.2) 4.8.5`

**Comment by Romz24** [comment]
I found the solution, I reinstalled the manual [cmake](https://cmake.org/), now I can compile without errors.

You can close this topic.
